name: tests workflow
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v1"
      - uses: "actions/setup-node@v1"
        with:
          node-version: 12.x
      - run: npm install
      - run: npm test
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v1"
      - uses: "actions/setup-node@v1"
        with:
          node-version: 12.x
      - run: npm audit --production
